### ISSUE TITLE
error Error: Could not load the default credentials.

### ISSUE THREAD

**Issue by Xevaltan** [gustavocardoso/txt2audio#10]
Hello! I have an error when i'm using it. That come from google i think.

Error : `error Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.`

Help me please

**Comment by gustavocardoso** [comment]
Hey!

Did you try the Google documentation? You should create the credentials, download the file and set an environment variable pointing to it!
