### ISSUE TITLE
Default Credentials

### ISSUE THREAD

**Issue by Gustavomdcl** [gustavocardoso/txt2audio#4]
Hello! Great project!

I am having this error:

`error Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.`

It would be nice to have some arguments in order to insert our credentials.

Until then, how can I deal with this error?

Thanks and keep up the good work!

**Comment by gustavocardoso** [comment]
Hey, man!

Thanks for opening this issue.

Did you follow the steps on this page (https://cloud.google.com/text-to-speech/docs/quickstart-client-libraries)? You need to go through all the processes described in the "Before you begin" section.

When you finish it, you will be able to download a son file with your credentials. Then, you have to set an environment variable with the path to that son file. The Google text to speech lib will look for this variable to validate your credentials.

Did I make myself clear?

:)

Thank you!

**Comment by gustavocardoso** [comment]
Can I close this issue!?!

**Comment by Gustavomdcl** [comment]
Hey gus, sorry!

I did manage to do it, thanks. I just forgot to reply you here, sorry! xD

Yes you can!
